version: '3'
services:
  auth-service:
    build:
      context: ./auth-service
    image: your-dockerhub-repo/auth-service:${IMAGE_TAG}
  order-service:
    build:
      context: ./order-service
    image: your-dockerhub-repo/order-service:${IMAGE_TAG}
  customer-service:
    build:
      context: ./customer-service
    image: your-dockerhub-repo/customer-service:${IMAGE_TAG}
  inventory-service:
    build:
      context: ./inventory-service
    image: your-dockerhub-repo/inventory-service:${IMAGE_TAG}
